package rag

import (
	"testqdrant/internal/llm"
)

// Legal system prompt — generalised for all Indian legal corpora.
const legalSystemPrompt = `You are an AI research assistant specialising in Indian law. Your knowledge covers the Indian Constitution, Bharatiya Nyaya Sanhita (BNS) 2023, Bharatiya Nagarik Suraksha Sanhita (BNSS) 2023, Bharatiya Sakshya Adhiniyam (BSA) 2023, and Indian case law.

Rules:
1. Answer ONLY from the provided legal context. Do not use knowledge outside the context.
2. Always cite the exact provision (e.g., "Section 103 BNS", "Article 21 Constitution").
3. If multiple provisions are relevant, cite each one clearly.
4. If the answer is NOT in the provided context, say: "Insufficient authoritative context is available in the database to answer this legal query accurately. Please consult a qualified advocate."
5. If a provision has been superseded (marked with ⚠ NOTE), clearly state that the older provision has been replaced and cite the new provision.
6. Keep language clear — accessible to both legal professionals and laypersons.`

// Compliance disclaimer — injected per COMPLIANCE_REGISTER.md §2.2.
const complianceDisclaimer = `
IMPORTANT: This response is generated by AI and is intended for research assistance only. It is not legal advice. All cited statutes and judgments should be verified against primary sources. Consult a qualified advocate before taking any legal action.`

// BuildMessages constructs the LLM message sequence from assembled context and query.
func BuildMessages(query string, contextWindow ContextWindow) []llm.ChatMessage {
	system := legalSystemPrompt + complianceDisclaimer

	userContent := "Legal context:\n\n" + contextWindow.Text + "\n\nQuestion: " + query + "\n\nAnswer (with provision citations):"

	return []llm.ChatMessage{
		{Role: "system", Content: system},
		{Role: "user", Content: userContent},
	}
}

// AbstentionMessage returns the standard abstention response.
func AbstentionMessage(reason string) string {
	switch reason {
	case "low_confidence":
		return "Insufficient authoritative context is available in the database to answer this legal query accurately. The retrieved materials do not provide a definitive answer. Please consult a qualified advocate or refer to the primary statute/judgment directly."
	case "off_corpus":
		return "This query does not appear to relate to the indexed legal corpus. Please rephrase your question or consult a qualified advocate."
	case "injection_detected":
		return "This query could not be processed. Please rephrase your question as a legal research query."
	default:
		return "Insufficient authoritative context is available. Please consult a qualified advocate."
	}
}
